"""Add 2FA fields to User model with server default

Revision ID: d986d46bbb10
Revises: bb057a0b58da
Create Date: 2025-06-23 16:45:10.474365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd986d46bbb10'
down_revision = 'bb057a0b58da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tfa_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tfa_enabled', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tfa_enabled')
        batch_op.drop_column('tfa_secret')

    # ### end Alembic commands ###
